<a href="https://colab.research.google.com/github/pdd1230/colab_test/blob/main/Hello_World.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print('Hello World')

Hello World


**굵은 텍스트**
*이탤릭체 텍스트*
# 새 섹션


```
# 코드로 형식 지정됨
```
[네이버](https://naver.com)
![00.파이썬설치 및 설정_01_새파일생성.PNG]()


> 인용구 추가


1.   항목 추가
2.   항목 추가



*   항목 추가
*   항목 추가



---

\:

:






In [3]:
a = [10, 20, 30]                  # list
b = (10, 20, 30)                  # tuple
c = {10, 20, 30}                  # set
d = {"name": "kim", "age": 20}    # dict

print(type(a))
print(type(b))
print(type(c))
print(type(d))

<class 'list'>
<class 'tuple'>
<class 'set'>
<class 'dict'>


In [7]:
import numpy as np

a = np.array([10, 20, 30])
# a = np.array([[10, 20, 30], [40, 50, 60]])
# ndarray → 수치 계산을 위한 배열
print(a)
print(type(a))

[10 20 30]
<class 'numpy.ndarray'>


In [10]:
import numpy as np
import pandas as pd

a = [10, 20, 30]   # 리스트
b = np.array(a)    # ndarray 배열
s = pd.Series(b)   #

# print(a)
# print(b)
print(s)
print()
print(type(a))   # <class 'list'>
print(type(b))   # <class 'numpy.ndarray'>
print(type(s))   # <class 'pandas.Series'>

0    10
1    20
2    30
dtype: int64

<class 'list'>
<class 'numpy.ndarray'>
<class 'pandas.core.series.Series'>


In [12]:
import numpy as np
import pandas as pd

a =[[10, 20, 30], [40,50,60]]   # 리스트
b = np.array(a)    # ndarray 배열
s = pd.DataFrame(b)   #

print(a)
print(b)
print(s)
print()
print(type(a))   # <class 'list'>
print(type(b))   # <class 'numpy.ndarray'>
print(type(s))   # <class 'pandas.DataFrame'>

[[10, 20, 30], [40, 50, 60]]
[[10 20 30]
 [40 50 60]]
    0   1   2
0  10  20  30
1  40  50  60

<class 'list'>
<class 'numpy.ndarray'>
<class 'pandas.core.frame.DataFrame'>


In [14]:
import torch

x = torch.tensor([10, 20, 30])
print(x)
print(type(x))
# Tensor
# → 딥러닝 계산에서 사용하는 다차원 데이터

tensor([10, 20, 30])
<class 'torch.Tensor'>


In [15]:
# numpy 배열의 연산

arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

# 사칙연산
print('numpy 배열 더하기 = \n', arr1 + arr2)
print('numpy 배열 빼기 = \n', arr2 - arr1)
print('numpy 배열 곱하기 = \n', arr1 * arr2)
print('numpy 배열 나누기 = \n', arr2 / arr1)

numpy 배열 더하기 = 
 [[ 8 10 12]
 [14 16 18]]
numpy 배열 빼기 = 
 [[6 6 6]
 [6 6 6]]
numpy 배열 곱하기 = 
 [[ 7 16 27]
 [40 55 72]]
numpy 배열 나누기 = 
 [[7.  4.  3. ]
 [2.5 2.2 2. ]]


# [넘파이 https://numpy.org/](https://numpy.org/)